---
title: "classwork-Thursday-3-9"
author: "Mehdi Nojoumi"
date: "March 9, 2017"
output: html_document
---

```{r}
#install.packages("paleotree")
#install.packages("paleobioDB")
library(paleobioDB)
library(paleotree)
data(graptPBDB)
head(graptOccPBDB)

#get species sorted occurance
occSpecies<-taxonSortPBDBocc(graptOccPBDB,rank = "species")
head(occSpecies)



#for Genera
#OccGenera<-taxonSortPBDBocc(graptTaxaPBDB, rank = "genus")


#convert occurance data to "timelist" format
graptTimeSpecies<-occData2timeList(occList = occSpecies)

#for Genera
#graptTimeGenus<-occData2timeList(occList = occGenera)


#plot species occurances
plotOccData(occSpecies,groupLabel = "species")

#plot diversity through time
taxicDivDisc(graptTimeSpecies)

#pdf(file="dtt.pdf")
#taxicDivDisc((graptTimeSpecies))
#taxicDivDisc((graptTimeGenera))
#taxicDivDisc((graptTimeFamily))
#dev.off()

```


```{r}
#install.packages("forcats")
library(forcats)
library(ggplot2)
canids <- read.csv("~/Desktop/eeb-177/homework/canids-genus-ranges.csv", header = F, as.is = T)
names(canids) <- c("genus", "minage", "maxage")
head(canids)

canid_occ <- ggplot(canids, aes( genus, ymin = maxage, ymax=minage, colour = genus))
canid_occ <- canid_occ + geom_linerange()+ theme(legend.position="none")+ coord_flip()+  theme(axis.text.y = element_text(size=3))+ theme(axis.ticks.y=element_blank()) + scale_y_continuous(limits=c(0, 40), expand = c(0, 0), breaks=c(0, 10, 20, 30, 40)) + labs(title = "Canid Fossil Occurrences", x = "Genera", y = "Ma ago") + theme(plot.title = element_text(hjust = 0.5, size=22, face = "bold"), axis.title =element_text(size=20))
canid_occ

```



